apiVersion: v1
kind: Secret
metadata:
  name: pez-k8s
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/rwejlgaard/pez-k8s.git
