apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://bitnami-labs.github.io/sealed-secrets
