apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 44.3.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
  #valuesFrom:
  #- kind: ConfigMap
    #name: prometheus-values
