apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: paris-pez-sh
  namespace: istio-system
spec:
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https-443
      number: 443
      protocol: HTTPS
    tls:
      credentialName: wild-global-tls
      mode: SIMPLE
