apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: prometheus-oper-istio-controlplane
  namespace: istio-system
spec:
  endpoints:
  - interval: 15s
    port: http-monitoring
  - interval: 15s
    port: http-policy-monitoring
  jobLabel: istio
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
    - key: istio
      operator: In
      values:
      - mixer
      - pilot
      - galley
      - citadel
      - sidecar-injector
