apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-latest
  namespace: system-upgrade
spec:
  concurrency: 1
  version: v1.25.5-rc3+k3s1
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/arch # All nodes
        operator: Exists
  serviceAccountName: system-upgrade
  drain:
    force: true
  upgrade:
    image: rancher/k3s-upgrade
