apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: prometheus
  namespace: monitoring
spec:
  resourceSelectors:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2 
      kind: HelmRepository
      name: prometheus
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: prometheus
    - apiVersion: v1
      kind: ConfigMap
      name: prometheus-values
    - apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      name: prometheus
  placement:
    clusterAffinity:
      clusterNames: []
