apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../istio
  - ../../sealed-secrets
  - ../../grafana-cloud
  - ingressgateway.yaml
  - shared-gateway.yaml
  - k8s-monitoring.yaml
  - karpenter
