kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
  encryptedData:
    admin-password: AgCBAUn9pDy2RXQ/q+h8k+NbQa2Jqdtn6DUrydEg4XrJrCpMeXBz3ukBXe3nsm88BHOU2EhjYbaTD7aRBGqpPLyP67MNeFMbTQoYlllZRq4mvcjL30POdeCJjzo2zZDvry2zWdE+UnwHTt3NrKU4x0QmMDsbGtekM1YDolGobolHF3o/QYYlKR/c3Yl6BMBablV0jDe/f9yH7PFTLUSGz8btrRkOMELjoHZSW/D+S/HbpAnepY5C1Uykxd7fC+p56vN7Ex4Qadda3eWwbROqSaMt7qcjv6JJkiKFcJIXCuBmXfWZLSr4yIG5Gowf8qEWukq9M1GMVNjPtx2xmmQVodnYPwzZavIrzzyORvN0rRqnQn7GAhBCXxAyfHjEeg7T+GI0yS3GPUgKeUxyZ0o5MLqUStGWmE6PGZRLkAxhG8rVKuGtLgkrFPyb90Sb2iDclNDTKQWnsA+BFIzOAtJAS6z6NtNJkPLq5IGwSDNewWXu0MV3/M2+Dq3wbGM3YIQ9b/MPcyFD8UsqDVLza+YqTX7kOk0DhgmIxKLQyg3i46S2XRQktu86LLIJG3XR30IfQqsSQnDhhHBYP/fCoOPLv1wcNjq/WTweuaQZwFJTN6BjRpI2fGxujjnDlEEVU7gH0a49U0nQD2ctiux4/Owxguq7INX3PN7/EYTkkDLKya7CooJeLnMUXNzh5Fp1q+GnFWWVcIpW8LROzaU=
    admin-user: AgBZVgqArfJX9z6BM5MtQ+tX5kZN4o+hZSqoTrnoiSSIEkn1zYbpeJiQveAOMeXZbi33CmIIrGA+yN1zAD4FepVKGe3y4LnTydJGce2MiYovYKn5bE+SDyCs2hnMKdN+JcoiMnxLczjXcbNlPqlameGTb5+x+ct2Y+v15ZHn712B5sLoukMJYSb7qMtHPTpamrR+jnYtYocVwcDkeRcT15fYMnnX+uFG0ZuMMcqJrU4yLEi/0U7JpJoia5zdrvDFqas2tFI/mkdJLKKhKjkAu9CIvU67YqyzguB4qy8Sh8hp7DLSwk/5T06ZegZy5D6W9T/nkxdk3qKAnVgsygrbLyzZptA4u7Onm7nwn+nL7DaTtUYL3XXdNOxPjVJPrrw8ZUB/9kMnqO7tVs+Wl8DLu1hvR/PC2oQXyWDYGmNcn9yVqVgycQTjBJtXzT4TQ8bpOaUDsDc7dy6WNfl/p7OICtMMzhWhiCCWUnn/YYyYUF49vqeryWF5Vo8mopb/xM49u1Hios1+irauVDmia27HhUhtQLBpFcCceHpLGNrb+GWZZUKVb2ia/KovC2Ta5U40Wuy6IrDHc25nx4e65RFsK7S2F5NX6gvLbbiCijBbNlkjumBSM2p2tchMBpUvNN5CB5x0Oy7fpWX/fmk8X3NYyEGo2OzEimktdCwIN041brAULJipDGKQdWkky2x3GXH0C0t8ek4=
