apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCNZOZneyi40y62WBECRClqFDexXcKHW+NjGhn1B6yv3XVlKJnhiAQ4bDFMUhOvl9FFd/Ep4CPCcuPAFBaZGe2KE/eF8f4wNYBlEiW/0zNWKDhywtqEpG/m6eRvWZh/j7bzPqswHQr5Fqsgr4TzDjwLr5X9HHUJNKpx80kKAav1WUzGeWIZ8j/UzZzX2GoJ7WAnc+nMZ7CwYbaYnE120sd8IXI7W89uc3iyRTjNSOXwnZs/zlS6JXsNP2evXaQi93OyZBdkzgB+ktEEDq+VJsv0ReoqCURjBEEUCOfOYOZJhCp5rcGgsHqyE/tBmLw5sJPQVwgAbfIsOCEjLpqQsIaUeAyXoaAf1XfbdT7Tw3gWqbC50FmivC9K97bNJfIPPgfuAHdGRqt3T2OVnmhm662EklLRVZmSwNgTjttIrvD17IKF+Q62AmIsBBAmpezkNJMsCmObAY00c4Vhqs4j+yTupz7BGcszQvciRDbBHkYVOfDp7wOkzwAZTI0CPKsT55ViUiT+HFHIY+jMykCJsIuAfN4cTjiDN6U7e8PPGWwtoN/ANbObv3xBFOK0Ty3Cfqk00ae5YMPQxNDdDxxkwEwixZ48nwfqScgGuwVSfFjUmJTdkn8vSnjcxduwJ4dhkE4ysaFSr2/w1/Ugxg1UEIvBOPYsO3BbXn28f3IGNe3G5dsS/4dHCmhrR9w3F9vLhrBy88b1NmVPUy8=
    admin-user: AgCMw8lAxpVnAqncSyXp5U43NN8seSCZvl0mfHRFRB7AGqwqyhZT7dZL5x6SyyirzcgZu/lOgVqUuc9/hhRXs3oojrJOSwvCaoE94WSZqnR3ZZ1B2bsN7HBpZ1Q2pmneFJ/Cz46ldwS/lNqCL/n4oZNWex0YsY79OD9+dhVeWwOpMtpfdB7dzjmINOmQzfjwjmIqzgUiiTLNO5ymSQLBKJXOlyBMTieDhnSMjNsr+VzAGRGf7V/vLzdXU61WnFr9q2A3G96dJIuUHEf+b75L+2vVnPtYZZgd8N6mPNG5E0H9CD1D6R7VmpifmcpR7F5zliMa9XzyqisUCToIHYI98wgqy1ZmuxGW5Ce5xXZ6xkmTVJOT59VNoPt9wxAafvgLyUhzphCBFznUT/O9Qv4k42+27pwcW98xXcb13PGS1iHTEcJlXxH97KDCN/bMJZixS245Jjeoj557m/roTweI6i/LZ8jVmQjdne585WNZOAL6AcaRYgafhf3vECtXk7cH/YV4WFd91w7qfl0k5UlOdilBeJUkuCyGJiLFRgjD0oirHH9bepUsu+7RO8p6YlXWyoZNh5XdHIBATGRy8dVBWwC8ynkDEH/t4/ezAbHV/t5x6YXKhE5M4ethkhpk60DTPKwv0/OiLvschWaYQ4g2W4wFD7HNl8C6VMWnzqk547pGzxI5oW0ywwxs7nxqDpQPFtqLD/8=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque

