apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 6.45.1
      sourceRef:
        kind: HelmRepository
        name: grafana
  valuesFrom:
  - kind: ConfigMap
    name: grafana-values
