apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 5m
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
