apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 5m
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: 3.8.3
      sourceRef:
        kind: HelmRepository
        name: metrics-server
