apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pez-k8s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/rwejlgaard/pez-k8s.git
    targetRevision: argocd-migration
    path: argocd/applications/.
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
