apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  hosts:
  - argocd.global.pez.sh
  gateways:
  - istio-system/global-pez-sh
  http:
  - route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
