apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pez-sh
  namespace: pezsh
  labels:
    virtualservice.pez.sh/mutation: enabled
spec:
  hosts:
  - pez-sh.london.pez.sh
  - pez-sh.paris.pez.sh
  - pez-sh.copenhagen.pez.sh
  gateways:
  - istio-system/london-pez-sh
  - istio-system/paris-pez-sh
  - istio-system/copenhagen-pez-sh
  
  http:
  - route:
    - destination:
        host: pez-sh.pezsh.svc.cluster.local
