apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: operator
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
