apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/rwejlgaard/pez-k8s.git
    targetRevision: argocd-migration
    path: prometheus-operator/.
  destination:
    server: https://kubernetes.default.svc
