apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-custom-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/rwejlgaard/pez-k8s.git
    targetRevision: HEAD
    path: kyverno-custom-policies/.
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
