apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-stock-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
      - Replace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 2.7.2
    helm:
      releaseName: kyverno-stock-policies
      values: |-
        podSecuritySeverity: low
        policyExclude:
          disallow-host-path:
            any:
            - resources:
                kinds:
                - Pod
                namespaces:
                - istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
