apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.1
    helm:
      releaseName: sealed-secrets-controller
      values: |
        secretName: sealed-secrets-key
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
