apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemonitors
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/rwejlgaard/pez-k8s.git
    targetRevision: uber-cluster
    path: servicemonitors/.
  destination:
    server: https://kubernetes.default.svc
