apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: flux
spec:
  placement:
    clusterAffinity:
      clusterNames: []
  resourceSelectors:
  - apiVersion: v1
    kind: Namespace
    name: flux-system
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: alerts.notification.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: buckets.source.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: gitrepositories.source.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: helmcharts.source.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: helmreleases.helm.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: helmrepositories.source.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: kustomizations.kustomize.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ocirepositories.source.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: providers.notification.toolkit.fluxcd.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: receivers.notification.toolkit.fluxcd.io
  - apiVersion: v1
    kind: ServiceAccount
    name: helm-controller
  - apiVersion: v1
    kind: ServiceAccount
    name: kustomize-controller
  - apiVersion: v1
    kind: ServiceAccount
    name: notification-controller
  - apiVersion: v1
    kind: ServiceAccount
    name: source-controller
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: crd-controller-flux-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: cluster-reconciler-flux-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: crd-controller-flux-system
  - apiVersion: v1
    kind: Service
    name: notification-controller
  - apiVersion: v1
    kind: Service
    name: source-controller
  - apiVersion: v1
    kind: Service
    name: webhook-receiver
  - apiVersion: apps/v1
    kind: Deployment
    name: helm-controller
  - apiVersion: apps/v1
    kind: Deployment
    name: kustomize-controller
  - apiVersion: apps/v1
    kind: Deployment
    name: notification-controller
  - apiVersion: apps/v1
    kind: Deployment
    name: source-controller
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: allow-egress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: allow-scraping
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: allow-webhooks
