apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: virtualservice-host-mutator
webhooks:
  - name: virtualservice-host-mutator.webhooks.svc
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQXRpZ0F3SUJBZ0lRS0JwcDVFRnUweGVTeWVmZGg3T2VRREFLQmdncWhrak9QUVFEQWpBak1TRXcKSHdZRFZRUUREQmhyTTNNdGMyVnlkbVZ5TFdOaFFERTJOamt6TWpVMk5UTXdIaGNOTWpJeE1qRTRNREF4TXpBMgpXaGNOTWpNeE1qRTRNREF4TXpBMldqQTVNUlV3RXdZRFZRUUtFd3h6ZVhOMFpXMDZibTlrWlhNeElEQWVCZ05WCkJBTU1GM041YzNSbGJUcHViMlJsT205MmFDNXdaWG91YzJnN01JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0MKQVE4QU1JSUJDZ0tDQVFFQXZvdzBmZjA3MUw0ZmpUVTF4Z05lTXd1cjlvVjdWYVpoZ3VDajU1c09rMjhYekRVRAptdUk1Y1doOGFORGliRHRicFpteUx3MngrdHBVTU1TTGtGM1d3aVNaak9iK0U3V0hjRkppOWQ1b0M0MU9tQ0MyCk1PK1Z3Y2I2UFJwTURTbXdxOHB4WEJBNy9pS2dVYlVpZWsyZTMwZGc2NWVwWkxvZEJrLy9KZGJNT3Z0N0pWNHIKQmlDRHJlYkhxZjh2bGlERkI0eCsvWTVvQ3VGMTZsc211TXJ2MXdDOXAxWU5UT2dmQjRzQUVPSDM5TVI2aU9LSgp4VTJYakxGNFhVZnh1cGIyb0xod1VOWkRZbjVxZDdhd0lGOTdCOFJSWkFTYWRCTk03d2hIYVIrVzlmWVVvRG82CmxQZmN6SlcyMittRzk3NkFFdGdKRldUTG5hRjhWNmJtNmM0ZVZ3SURBUUFCbzRJQkN6Q0NBUWN3RGdZRFZSMFAKQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRApWUjBqQkJnd0ZvQVVyUk9iRHFOb2xFZ2FEV1poczR4S00xR1dzZ2N3Z2JBR0ExVWRFUVNCcURDQnBZSWJkbWx5CmRIVmhiSE5sY25acFkyVXRhRzl6ZEMxdGRYUmhkRzl5Z2lSMmFYSjBkV0ZzYzJWeWRtbGpaUzFvYjNOMExXMTEKZEdGMGIzSXVkMlZpYUc5dmEzT0NLSFpwY25SMVlXeHpaWEoyYVdObExXaHZjM1F0YlhWMFlYUnZjaTUzWldKbwpiMjlyY3k1emRtT0NOblpwY25SMVlXeHpaWEoyYVdObExXaHZjM1F0YlhWMFlYUnZjaTUzWldKb2IyOXJjeTV6CmRtTXVZMngxYzNSbGNpNXNiMk5oYkRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCQmVPWWRrcXVCSW5rSFpZY2wKN083c2t3NzJqR0RZeUhhaDVERm1VMmJLWXdJZ1Nma3paWm1JZU15OERvanBHWUdpRElEKzhRUzdmT2lCY1ZlUgp0eHhhNjY0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      #caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTmprek1qVTJOVE13SGhjTk1qSXhNVEkwTWpFek5ERXpXaGNOTXpJeE1USXhNakV6TkRFegpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTmprek1qVTJOVE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUV2tNcnZ3eXJYNFhXMHpIaGt5ODN6a3I1NE5janl0OGsvYlZ2REVHcnAKUmJqWG1pU0wzZEVzangxSDhuU0NxamZoT3ZZUE85T2RnYlJRaHl5cTZxQjZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXJST2JEcU5vbEVnYURXWmhzNHhLCk0xR1dzZ2N3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU5qYytuOG1jRU1GNVlzZlpQMy9NYXA2RkpOZnRmcW4KVTZCajlIYWhTdFh0QWlBb09RMS9Dd2x2Vm9aTUwremxod1p0R3hWMmU2RmRsTDFleHZjb1JoZHAxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: virtualservice-host-mutator
        namespace: webhooks
        path: "/mutate"
        port: 443
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["networking.istio.io"]
        apiVersions: ["*"]
        resources: ["virtualservices", "VirtualService"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        virtualservice.pez.sh/mutation: enabled
    objectSelector:
      matchLabels:
        #app: virtualservice-host-mutator
        virtualservice.pez.sh/mutation: enabled
    sideEffects: None
    admissionReviewVersions:
      - v1
      - v1beta1
