name: Apply Manifests

# Controls when the workflow will run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install Kubectl
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          mv ./kubectl /usr/local/bin/kubectl

      - name: Deploy
        shell: bash
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
          KUBE_CONTEXT: pez-london
        run: |
          cd $GITHUB_WORKSPACE
          ./apply.sh

