name: Apply Manifests

# Controls when the workflow will run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Kubectl
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl

      - name: Deploy
        shell: bash
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
          KUBE_CONTEXT: pez-london
        run: |
          cd $GITHUB_WORKSPACE 
          for file in `ls **/*.yaml`
          do
            ./kubectl apply -f $file
          done
