name: Apply Manifests

# Controls when the workflow will run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install kubeconfig
        shell: bash
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo $KUBECONFIG > ~/.kube/config

      - name: Install Kubectl
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl

      - name: Deploy
        shell: bash
        run: |
          for file in `ls **/*.yaml`
          do
            echo $file
            ./kubectl apply -f $file
          done
